### ISSUE TITLE
wrong md5sum

### ISSUE THREAD

**Issue by rclar-in-dc** [FabioLolix/PKGBUILD-AUR_fix#1]
I'm getting a different md5sum on the tui-mater.tar.gz file, yet it doesn't seemed to have change on savannah in a number of years. What is the correct md5sum?

**Comment by FabioLolix** [comment]
Hello, I had only imported the tui pkgbuild 'as is' without further modication, and later deleted it.

The pkgbuild is a disaster, it never had correlation between source and pkgver, and failed to actually produce an usable Arch package, I given up on it.
