### ISSUE TITLE
tokodon-git is missing from this repo

### ISSUE THREAD

**Issue by jahway603** [FabioLolix/PKGBUILD-AUR_fix#11]
[This PKGBUILD](https://aur.archlinux.org/packages/tokodon-git) is not in this Github repo.

**Comment by FabioLolix** [comment]
Yes and not the only one missing, will update in the next days

**Comment by FabioLolix** [comment]
It has been added here

https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/4536723f33758fb97359358f2856f7f64ea356ff
https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/581ff486b2063fac6f7ee963c428286103e8f4f9
https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/581ff486b2063fac6f7ee963c428286103e8f4f9
