### ISSUE TITLE
Borked heroic packages

### ISSUE THREAD

**Issue by imLinguin** [FabioLolix/PKGBUILD-AUR_fix#42]
after recent (2.15.0) update the packages maintained by you (heroic-games-launcher, heroic-games-launcher-git) don't work properly, due to changed build process. 

Namely you need to add `pnpm run download-helper-binaries` after the `pnpm install` step

**Comment by FabioLolix** [comment]
Fixed thanks https://github.com/FabioLolix/PKGBUILD-AUR_fix/commit/6041be092d934c40b5507b34c453eeaaf1d48ae5
